import Head from 'next/head';
import Link from 'next/link';
import List from '../../components/List';
import { AudioOutlined } from '@ant-design/icons';
import { Input, Space } from 'antd';

export default function Home() {
  const { Search } = Input;
  const suffix = (
    <AudioOutlined
      style={{
        fontSize: 16,
        color: '#1890ff',
      }}
    />
  );
  const onSearch = (value) => console.log(value);

  return (
    <>
      <Head>
        <title>찬양단 곡 검색 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="plus_btn">
        <Link href="/">+</Link>
      </div>

      <Search
        placeholder="검색어를 입력하세요"
        onSearch={onSearch}
        style={{
          width: '100%',
          margin: '50px auto 20px',
        }}
      />

      <div className="index_container">
        <Link href="/sub">
          <List />
        </Link>
        <List />
        <List />
        <List />
        <List />
      </div>
    </>
  );
}
